name: GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate HTML
      uses: rhtconsulting/asciidoctor-action@v1.0
      with:
        args: asciidoctor -D build -o index.html README.adoc
    
    - name: Copy assets to build/
      run: cp -r assets build/
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: build 
