name: GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: asciidoctor
      uses: rhtconsulting/asciidoctor-action@master
      with:
        args: asciidoctor README.adoc
        
    - name: ls DEBUG
      run: ls -al
